title: DNHS Project Frostbyte
description: "Camping and National Parks and Recreation Guide and Discussion Site"
owner_name: CSP Period 1 Group Frostbyte
github_username: blackstar3092
github_repo: "frostbyte_frontend" 
baseurl: "/frostbyte_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/search.md
  - navigation/about/home.md
  - navigation/camping/home.md
  - navigation/national_parks/home.md

Server: https://frostbyte.stu.nighthawkcodingsociety.com/
Domain: stu.nighthawkcodingsociety.com
Subdomain: frostbyte
